digite = input('Escreva alguma coisa: ')
print('È alfanumérico? ', digite.isalnum())
print('È minúsculo? ', digite.islower())
print('È um espaço? ', digite.isspace())
print('È um número decimal? ', digite.isdecimal())
print('Está capitalizada? ', digite.istitle())
print('Foram digitados {} caracteres'.format(len(digite)))
print(digite[0:4])
print(digite[-2])
print(type(digite))
